test

diff --git a/.drone.yml b/.drone.yml
--- a/.drone.yml
+++ b/.drone.yml
@@ -16,9 +16,10 @@ steps:
     #   SOME_VAL1: 598408
     commands:
       - echo "$DRONE_BRANCH"
-      - if [[ "$DRONE_BRANCH" =~ ^(?![a-zA-z]*-[0-9]*) ]]; then |
-        echo "Valid branch name" |
-        else |
-        echo "Invalid branch name"; exit 1 |
+      - |
+        if [[ "$DRONE_BRANCH" =~ ^(?![a-zA-z]*-[0-9]*) ]]; then 
+          echo "Valid branch name" 
+        else 
+          echo "Invalid branch name"; exit 1 
         fi
       - echo "$SOME_VAL1"
